### ISSUE TITLE
Crash at startup Android when using API level 23

### ISSUE THREAD

**Issue by deleteescape** [mradosta/cordova-plugin-streaming#1]
Cordova app for Android crashes at startup and won't start when using this plugin.

Here's the logcat from startup:

```
--------- beginning of crash
04-15 16:44:42.023 16034 16257 V RadioManager: RadioManagerLog : Requested to connect service.
04-15 16:44:42.374 16034 16034 E linker  : /data/app/nl.apptest-1/lib/arm/libaacdecoder.so: has text relocations
04-15 16:44:42.400 16034 16034 E AndroidRuntime: FATAL EXCEPTION: main
04-15 16:44:42.400 16034 16034 E AndroidRuntime: Process: nl.apptest, PID: 16034
04-15 16:44:42.400 16034 16034 E AndroidRuntime: Theme: themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
04-15 16:44:42.400 16034 16034 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/nl.apptest-1/lib/arm/libaacdecoder.so: has text relocations
04-15 16:44:42.400 16034 16034 E AndroidRuntime:    at java.lang.Runtime.loadLibrary(Runtime.java:372)
04-15 16:44:42.400 16034 16034 E AndroidRuntime:    at java.lang.System.loadLibrary(System.java:1076)
04-15 16:44:42.400 16034 16034 E AndroidRuntime:    at com.spoledge.aacdecoder.Decoder.loadLibrary(Decoder.java:187)
04-15 16:44:42.400 16034 16034 E AndroidRuntime:    at com.spoledge.aacdecoder.Decoder.create(Decoder.java:221)
04-15 16:44:42.400 16034 16034 E AndroidRuntime:    at com.spoledge.aacdecoder.Decoder.create(Decoder.java:198)
04-15 16:44:42.400 16034 16034 E AndroidRuntime:    at com.spoledge.aacdecoder.AACPlayer.createDecoder(AACPlayer.java:508)
04-15 16:44:42.400 16034 16034 E AndroidRuntime:    at com.spoledge.aacdecoder.MultiPlayer.createDecoder(MultiPlayer.java:91)
04-15 16:44:42.400 16034 16034 E AndroidRuntime:    at com.spoledge.aacdecoder.AACPlayer.<init>(AACPlayer.java:130)
04-15 16:44:42.400 16034 16034 E AndroidRuntime:    at com.spoledge.aacdecoder.MultiPlayer.<init>(MultiPlayer.java:81)
04-15 16:44:42.400 16034 16034 E AndroidRuntime:    at com.imsd.radio.RadioPlayerService.getPlayer(RadioPlayerService.java:403)
04-15 16:44:42.400 16034 16034 E AndroidRuntime:    at com.imsd.radio.RadioPlayerService.onCreate(RadioPlayerService.java:215)
04-15 16:44:42.400 16034 16034 E AndroidRuntime:    at android.app.ActivityThread.handleCreateService(ActivityThread.java:2911)
04-15 16:44:42.400 16034 16034 E AndroidRuntime:    at android.app.ActivityThread.-wrap4(ActivityThread.java)
04-15 16:44:42.400 16034 16034 E AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1446)
04-15 16:44:42.400 16034 16034 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:102)
04-15 16:44:42.400 16034 16034 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:148)
04-15 16:44:42.400 16034 16034 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:5461)
04-15 16:44:42.400 16034 16034 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
04-15 16:44:42.400 16034 16034 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-15 16:44:42.400 16034 16034 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Does someone know why? I think it has to do with API level 23 I'm using with this one, because on API level 22 it works fine.
Thanks!

**Comment by GitUnLi** [comment]
Same,
 for me crashing too.

**Comment by mradosta** [comment]
Fixed in https://github.com/mradosta/cordova-plugin-streaming/commit/00e459e56ed2aa8b6e7e80fe744f83d7753a0cd8
Check comment on commit for details
